apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka-platform
spec:
  type: ExternalName
  # https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds
  externalName: host.docker.internal
  ports:
    - port: 9092
      name: port
